### ISSUE TITLE
Library Resource launcher icon conflict with prject launcher icon

### ISSUE THREAD

**Issue by InvertedX** [manolovn/colorbrewer#1]
you should delete drawable Launcher icon resource..it gives this error
`build\intermediates\res\debug\drawable-hdpi-v4\ic_launcher.png: error: Duplicate file.
 \build\intermediates\res\debug\mipmap-hdpi\ic_launcher.png: Original is here. The version qualifier may be implied.`
this library doesn't require launcher icon

**Comment by manolovn** [comment]
Hi, I can't reproduce the error you're talking about. can you give me more info?
Thx!

**Comment by InvertedX** [comment]
hello manolovn in your library res directory,you have lacher icons in there.you need remove that.i cant find that in you git repo. but i extracted your aar and found them.
![capxxture](https://cloud.githubusercontent.com/assets/6897265/12815997/d2582ec0-cb6f-11e5-8f50-5b2e9d8cfe5a.PNG)
.you need to update the library without those launcher icon..this is the cause of that error
`Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_app_icon) from AndroidManifest.xml:21:9-43
>     is also present at [com.manolovn:colorbrewer:1.0.0] AndroidManifest.xml:13:9-43 value=(@mipmap/ic_launcher)
>     Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:18:5-75:19 to override`
